add support for multiple remotes (get rid of SUNT_PATH variable)

diff --git a/sunt b/sunt
--- a/sunt
+++ b/sunt
@@ -3,6 +3,10 @@
 # License: GNU GPLv3
 
 IFS=$'\n'
+shopt -s extglob
+
+declare force all onremote compress destination_length file_path id
+declare -a destination
 
 die() {
     exit_code="$1"
@@ -31,18 +35,17 @@ usage() {
     printf "  SUNT_COMPRESS\t\tcommand used for compression\n"
     printf "  SUNT_DECOMPRESS\tcommand used for decompression\n"
     printf "  SUNT_HASH\t\tcommand used for translating file names\n"
-    printf "  SUNT_PATH\t\tpath under which every file in index should be under\n"
-    printf "  SUNT_DEST\t\tpath to the remote, in scp command fashion\n\n"
+    printf "  SUNT_DEST\t\tfour segments specifying name,connection command,remote path,local path separated by colon (can be repeated)\n\n"
     printf "By default %s tries to read variables from ~/.config/sunt file\n" "$NAME"
     exit 0
 }
 
 file_check() {
-    options="$1"
+    local -r options="$1"
     shift
     while [ "$#" -gt 0 ]
     do
-        for i in $(echo "$options" | sed 's/\(.\)/\1\n/g')
+        for i in $(sed 's/\(.\)/\1\n/g' <<< "$options")
         do
             case "$i" in 
                 e) #does not exists then exit
@@ -82,6 +85,7 @@ var_by_name() {
 }
 
 var_check() {
+    local val
     while [ "$#" -gt 0 ]
     do
         val="$(var_by_name "$1")"
@@ -91,7 +95,7 @@ var_check() {
 }
 
 varfile_check() {
-    options="$1"
+    local -r options="$1"
     shift
     [ $# -eq 0 ] && return
     while [ "$#" -gt 0 ]
@@ -107,75 +111,97 @@ f_list() {
     cat "$SUNT_INDEX"
 }
 
+find_path() {
+    local -r path="$(realpath "$1")"
+    local t
+    for ((i=0;i<destination_length;i+=4))
+    do
+        t="${destination[i+3]//$'\n'}"
+        export file_path="${path#$t/}"
+        [ "$file_path" != "$path" ] && { id="$i"; break; }
+    done
+}
+
 f_add() {
+    local name_hash dir options t
     while [ "$#" -gt 0 ]
     do
         file_check 'erw' "$1"
-        if realpath "$1" | grep -q "^$SUNT_PATH/"
-        then
-            name="$(realpath "$1" | sed "s#^$SUNT_PATH/##")"
-            name_hash="$(echo -n "$name" | $SUNT_HASH | sed 's/ .*//')"
-            [ -d "$1" ] && dir=1 || \
-                [ -f "$1" ] || { echo "$1 is not a file or directory" >/dev/stderr; shift; continue; }
-            [ -n "$dir" ] && options="d" || options="f"
-            [ -n "$compress" ] && options="${options}c"
-            [ -z "$force" ] && grep -q '^'"$name_hash;" "$SUNT_INDEX" && { echo "$1 is already declared" >/dev/stderr; shift; continue; }
-            sed -i "/^$name_hash;/d" "$SUNT_INDEX"
-            echo "$name_hash;$name;$options" >> "$SUNT_INDEX" && echo "added $1"
-        else
-            echo "$1 is not in $SUNT_PATH aka SUNT_PATH"
-        fi
+        find_path "$1"
+        [ -z "$id" ] && { echo "$1 is not in $SUNT_DEST aka SUNT_DEST" >/dev/stderr; shift continue; }
+        t="$(echo -n "$file_path" | $SUNT_HASH)"
+        name_hash="${t%% *}"
+        [ -d "$1" ] && dir=1 || \
+            [ -f "$1" ] || { echo "$1 is not a file or directory" >/dev/stderr; shift; continue; }
+        [ -n "$dir" ] && options="d" || options="f"
+        [ -n "$compress" ] && options="${options}c"
+        [ -z "$force" ] && grep -q '^'"$name_hash"$'\t' "$SUNT_INDEX" && { echo "$1 is already declared" >/dev/stderr; shift; continue; }
+        sed -i "/^$name_hash\t/d" "$SUNT_INDEX"
+        echo "$name_hash"$'\t'"$file_path"$'\t'"${destination[id]//$'\n'}"$'\t'"$options" >> "$SUNT_INDEX" && echo "added $1"
         shift
     done
 }
 
 f_delete() {
+    local t name_hash
     while [ "$#" -gt 0 ]
     do
-        name="$(realpath "$1" | sed "s#^$SUNT_PATH/##")"
-        name_hash="$(echo -n "$name" | $SUNT_HASH | sed 's/ .*//')"
-        grep -q '^'"$name_hash;" "$SUNT_INDEX" || echo "$1 not found" && \
-            sed -i "/^$name_hash;/d" "$SUNT_INDEX"
-        [ -n "$onremote" ] && ssh "$ssh_con" "rm \"$ssh_path/$name_hash\""
+        find_path "$1"
+        [ -z "$id" ] && { echo "$1 is not in $SUNT_DEST aka SUNT_DEST" >/dev/stderr; shift; continue; }
+        t="$(echo -n "$file_path" | $SUNT_HASH)"
+        name_hash="${t%% *}"
+        if grep -q '^'"$name_hash"$'\t' "$SUNT_INDEX"
+        then
+            sed -i "/^$name_hash\t/d" "$SUNT_INDEX"
+            [ -n "$onremote" ] && eval "${destination[id+1]//$'\n'} \"rm \"${destination[id+2]//$'\n'}/$name_hash\"\""
+        else
+            echo "$1 not found" >/dev/stderr
+        fi
         shift
     done
 }
 
 f_restore() {
+    local t name_hash com
     while [ "$#" -gt 0 ]
     do
-        name="$(realpath "$1" | sed "s#^$SUNT_PATH/##")"
-        name_hash="$(echo -n "$name" | $SUNT_HASH | sed 's/ .*//')"
-        line="$(grep '^'"$name_hash;" "$SUNT_INDEX")"
+        find_path "$1"
+        [ -z "$id" ] && { echo "$1 is not in $SUNT_DEST aka SUNT_DEST" >/dev/stderr; shift; continue; }
+        t="$(echo -n "$file_path" | $SUNT_HASH)"
+        name_hash="${t%% *}"
+        line="$(grep '^'"$name_hash"$'\t' "$SUNT_INDEX")"
         [ -z "$line" ] && { echo "$1 not found" >/dev/stderr; shift; continue; }
         [ -z "$force" ] && [ -e "$1" ] && { echo "$1 already exists" >/dev/stderr; shift; continue; }
-        ssh "$ssh_con" "[ -e \"$ssh_path/$name_hash\" ]" || { echo "$1 not found in storage" >/dev/stderr; shift; continue; }
-        com="ssh \"$ssh_con\" \"cat $ssh_path/$name_hash\" | $SUNT_DECRYPT"
-        case "$(echo "$line" | cut -d';' -f3)" in
-            f) eval "$com > \"$SUNT_PATH/$name\"";;
-            fc) eval "$com | $SUNT_DECOMPRESS > \"$SUNT_PATH/$name\"";;
-            d) eval "$com | tar -C \"\$(dirname \"$SUNT_PATH/$name\")\" -x";;
-            dc) eval "$com | $SUNT_DECOMPRESS | tar -C \"\$(dirname \"$SUNT_PATH/$name\")\" -x";;
+        eval "${destination[id+1]//$'\n'} \"[ -e \"${destination[id+2]//$'\n'}/$name_hash\" ]\"" || { echo "$1 not found in storage" >/dev/stderr; shift; continue; }
+        com="${destination[id+1]//$'\n'} \"cat ${destination[id+2]//$'\n'}/$name_hash\" | $SUNT_DECRYPT"
+        case "$(cut -d $'\t' -f4 <<< "$line")" in
+            f) eval "$com > \"${destination[id+3]//$'\n'}/$file_path\"";;
+            fc) eval "$com | $SUNT_DECOMPRESS > \"${destination[id+3]//$'\n'}/$file_path\"";;
+            d) eval "$com | tar -C \"\$(dirname \"${destination[id+3]//$'\n'}/$file_path\")\" -x";;
+            dc) eval "$com | $SUNT_DECOMPRESS | tar -C \"\$(dirname \"${destination[id+3]//$'\n'}/$file_path\")\" -x";;
         esac
         shift
     done
 }
 
 f_upload() {
+    local t name_hash com
     while [ "$#" -gt 0 ]
     do
-        name="$(realpath "$1" | sed "s#^$SUNT_PATH/##")"
-        name_hash="$(echo -n "$name" | $SUNT_HASH | sed 's/ .*//')"
-        line="$(grep '^'"$name_hash;" "$SUNT_INDEX")"
+        find_path "$1"
+        [ -z "$id" ] && { echo "$1 is not in $SUNT_DEST aka SUNT_DEST" >/dev/stderr; shift; continue; }
+        t="$(echo -n "$file_path" | $SUNT_HASH)"
+        name_hash="${t%% *}"
+        line="$(grep '^'"$name_hash"$'\t' "$SUNT_INDEX")"
         [ -z "$line" ] && { echo "$1 not found" >/dev/stderr; shift; continue; }
-        [ -z "$force" ] && ssh "$ssh_con" "[ -e \"$ssh_path/$name_hash\" ]" && { echo "$1 already exists" >/dev/stderr; shift; continue; }
-        case "$(echo "$line" | cut -d';' -f3)" in
-            f) com="cat \"$SUNT_PATH/$name\"";;
-            fc) com="cat \"$SUNT_PATH/$name\" | $SUNT_COMPRESS";;
-            d) com="tar -c -C \"\$(dirname \"$SUNT_PATH/$name\")\" \"\$(basename \"$name\")\"";;
-            dc) com="tar -c -C \"\$(dirname \"$SUNT_PATH/$name\")\" \"\$(basename \"$name\")\" | $SUNT_COMPRESS";;
+        [ -z "$force" ] &&  eval "${destination[id+1]//$'\n'} \"[ -e \"${destination[id+2]//$'\n'}/$name_hash\" ]\"" && { echo "$1 already exists" >/dev/stderr; shift; continue; }
+        case "$(cut -d $'\t' -f4 <<< "$line")" in
+            f) com="cat \"${destination[id+3]//$'\n'}/$file_path\"";;
+            fc) com="cat \"${destination[id+3]//$'\n'}/$file_path\" | $SUNT_COMPRESS";;
+            d) com="tar -c -C \"\$(dirname \"${destination[id+3]//$'\n'}/$file_path\")\" \"\$(basename \"$file_path\")\"";;
+            dc) com="tar -c -C \"\$(dirname \"${destination[id+3]//$'\n'}/$file_path\")\" \"\$(basename \"$file_path\")\" | $SUNT_COMPRESS";;
         esac
-        eval "$com | $SUNT_ENCRYPT | ssh \"$ssh_con\" \"cat > $ssh_path/$name_hash\"" && echo "uploaded $1"
+        eval "$com | $SUNT_ENCRYPT | ${destination[id+1]//$'\n'} \"cat > ${destination[id+2]//$'\n'}/$name_hash\"" && echo "uploaded $1"
         shift
     done
 }
@@ -186,13 +212,16 @@ f_au() {
 }
 
 f_index() {
-    eval "cat \"$SUNT_INDEX\" | $SUNT_COMPRESS | $SUNT_ENCRYPT | ssh \"$ssh_con\" \"cat > $ssh_path/index.gpg\""
+    for ((i=0;i<destination_length;i+=4))
+    do
+        eval "$SUNT_COMPRESS < \"$SUNT_INDEX\" | $SUNT_ENCRYPT | ${destination[i+1]//$'\n'} \"cat > ${destination[i+2]//$'\n'}/index.gpg\""
+    done
 }
 
 . ~/.config/sunt &>/dev/null
 
 varfile_check 'Efrw' SUNT_INDEX
-var_check SUNT_ENCRYPT SUNT_DECRYPT SUNT_COMPRESS SUNT_DECOMPRESS SUNT_HASH SUNT_PATH SUNT_DEST
+var_check SUNT_ENCRYPT SUNT_DECRYPT SUNT_COMPRESS SUNT_DECOMPRESS SUNT_HASH SUNT_DEST
 
 [ "$#" -eq 0 ] && usage
 case "$1" in
@@ -207,24 +236,26 @@ esac
 [ -z "$func" ] && die 1 "$1 incorrect command"
 shift
 
-while [ "$#" -gt 0 ]  && echo "$1" | grep -q '^-'
+while getopts 'farc' o
 do
-    case "$(echo "$1" | sed 's/^-//; s/\(.\).*/\1/')" in
-        f) force=1;;
-        a) all=1;;
-        r) onremote=1;;
-        c) compress=1;;
+    case "$o" in
+        f) force='1';;
+        a) all='1';;
+        r) onremote='1';;
+        c) compress='1';;
+        *) usage;;
     esac
-    shift
 done
+shift "$((OPTIND-1))"
 
-echo "$SUNT_DEST" | grep -q ':' || die 1 "$SUNT_DEST incorrect address"
-ssh_con="$(echo "$SUNT_DEST" | cut -d: -f1)"
-ssh_path="$(echo "$SUNT_DEST" | cut -d: -f2)"
+mapfile -t -d, destination <<< "$SUNT_DEST"
+[ "$((${#destination[@]}%4))" -ne '0' ] && die 1 "invalid SUNT_DEST"
+destination_length="${#destination[@]}"
 
-if [ -n "$all" ] && [ "$func" = "f_upload" -o "$func" = "f_restore" ]
-then
-    $func "$(cut -d';' -f2 < "$SUNT_INDEX" | sed 's,^,'"$SUNT_PATH/"',')"
-else
-    $func "$@"
-fi
+#if [ -n "$all" ] && [ "$func" = "f_upload" -o "$func" = "f_restore" ]
+#then
+#    $func "$(cut -d';' -f2 < "$SUNT_INDEX" | sed 's,^,'"$SUNT_PATH/"',')"
+#else
+#    $func "$@"
+#fi
+$func "$@"
